---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/nicholaswilde/notes
  pullPolicy: IfNotPresent
  tag: "version-ee287b9"

env: {}
  # TZ: "Europe/Amsterdam"
  # PUID: "1000"
  # PGID: "1000"

service:
  port:
    port: 8000

ingress:
  enabled: false

persistence:
  data:
    enabled: true
    emptyDir: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: "longhorn"


