---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/grav
  pullPolicy: IfNotPresent
  tag: "version-1.7.18"

# See more environment variables in the grav documentation
# https://github.com/linuxserver/docker-grav#parameters
env: {}
  # TZ:

service:
  port:
    port: 80

ingress:
  enabled: true

persistence:
  config:
    enabled: true
    emptyDir: false
    mountPath: /config
    accessmode: ReadWriteMany
    storageClass: "longhorn"
